import type { Metadata } from "next";
import {  Nunito_Sans } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvider";
import "../lib/fontawesome";

const nunitoSans =  Nunito_Sans({
  subsets: ["latin"],
  weight: [ "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-nunito",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dashboard App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunitoSans.variable}>
      <body className="">
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
